# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_register(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1050, 660)
    self.driver.find_element(By.LINK_TEXT, "Account").click()
    self.driver.find_element(By.CSS_SELECTOR, "#RegForm > input:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#RegForm > input:nth-child(1)").send_keys("joelnencil")
    self.driver.find_element(By.CSS_SELECTOR, "#RegForm > #email").send_keys("joel@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, "#RegForm > #password").send_keys("Jojima2003")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
  
